
spring:
  ##数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/orion?serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 351975711
    driver-class-name: com.mysql.cj.jdbc.Driver
    ###################以下为druid增加的配置###########################
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方
    filters: stat,wall
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

#  redis:
#    database: 0
#    timeout: 0
#    host: 127.0.0.1
#    port: 6379
#    password:
#    # 连接池最大连接数（使用负值表示没有限制）
#    pool:
#      maxActive: 100
#    # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      maxWait: -1
#    # 连接池中的最大空闲连接
#      maxIdle: 90
#    # 连接池中的最小空闲连接
#      minIdle: 0

  servlet:
    multipart:
      enabled: true
      max-file-size: 64MB
      max-request-size: 1024MB

mybatis:
  mapper-locations: classpath*:org/orion/**/dao/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true