SELECT TABLE_NAME, (DATA_LENGTH + INDEX_LENGTH) / 1048576 as size_Mb, TABLE_ROWS
FROM information_schema.tables
WHERE TABLE_SCHEMA = 'orion'
  AND TABLE_NAME = 'gf_backup_gallery_tx';

/*------------------------------*/
SHOW MASTER LOGS;
PURGE MASTER LOGS BEFORE '2019-07-20 23:00:00';

USE MYSQL;
SELECT USER,HOST FROM USER;
UPDATE USER SET HOST = '%' WHERE USER='ROOT';
FLUSH PRIVILEGES;