CREATE TABLE USER_TBL
(
  USER_ID                BIGINT PRIMARY KEY AUTO_INCREMENT,
  LOGIN_ID               VARCHAR(64) UNIQUE,
  USER_DOMAIN            VARCHAR(12)  NOT NULL,
  DISPLAY_NAME           VARCHAR(128) NOT NULL,
  PWD                    VARCHAR(128) NOT NULL,
  EMAIL                  VARCHAR(128),
  MOBILE_NO              VARCHAR(15),
  ACCT_STATUS            CHAR(1)      NOT NULL,
  REMARKS                VARCHAR(64),
  LOGIN_LAST_ATTEMPT_DT  DATETIME,
  LOGIN_LAST_SUCCESS_DT  DATETIME,
  LOGIN_FAIL_ATTEMPT_CNT INT,
  PWD_LAST_CHG_DT        DATETIME,
  PWD_CHG_REQUIRED       CHAR(1),
  ACCT_ACTIVATE_DT       DATETIME,
  ACCT_DEACTIVATE_DT     DATETIME,
  CREATED_AT             DATETIME,
  CREATED_BY             VARCHAR(64),
  UPDATED_AT             DATETIME,
  UPDATED_BY             VARCHAR(12),
  INDEX MOBILE_NO_IDX (MOBILE_NO)
);
ALTER TABLE USER_TBL AUTO_INCREMENT = 10000;

CREATE TABLE USER_LOGIN_HISTORY
(
  USER_ID    BIGINT      NOT NULL,
  LOGIN_ID   VARCHAR(64),
  LOGIN_TIME DATETIME    NOT NULL,
  IS_SUCCESS CHAR(1)     NOT NULL,
  CLIENT     VARCHAR(64),
  SESSION_ID VARCHAR(64),
  REASON     VARCHAR(64),
  INDEX LOGIN_ID_IDX (LOGIN_ID)
);


CREATE TABLE ERROR_CODE_MC
(
  ERROR_CODE VARCHAR(3) PRIMARY KEY,
  ERROR_DESC VARCHAR(256),
  ERROR_TYPE VARCHAR(1),
  ERROR_COND VARCHAR(255),
  CREATED_AT DATE,
  CREATED_BY VARCHAR(15),
  UPDATED_AT DATE,
  UPDATED_BY VARCHAR(15)
);

CREATE TABLE MODUEL_URL_ASSIGN
(
  MODUEL_ID   VARCHAR(64)  NOT NULL,
  MODULE_NAME VARCHAR(128) NOT NULL,
  MODUEL_DESC VARCHAR(128),
  FUNC_ID     VARCHAR(64)  NOT NULL,
  FUNC_NAME   VARCHAR(128),
  LEVEL       VARCHAR(2),
  URL         VARCHAR(512) NOT NULL,
  IS_SYSTEM   CHAR(1)      NOT NULL,
  REMARKS     VARCHAR(128)
);

CREATE TABLE ROLE_MODUEL_ASSIGN
(
  ROLE_ID    VARCHAR(15) NOT NULL,
  MODUEL_ID  VARCHAR(64) NOT NULL,
  FUNC_ID    VARCHAR(64) NOT NULL,
  PERMISSION VARCHAR(2)  NOT NULL
);

CREATE TABLE USER_ROLE_ASSIGN
(
  USER_ID BIGINT NOT NULL,
  ROLE_ID VARCHAR(15) NOT NULL,
  REMARKS VARCHAR(128)
);

CREATE TABLE BATCH_JOB_SCHEDUEL
(
  JOB_ID        VARCHAR(12) PRIMARY KEY ,
  NAME          VARCHAR(64)  NOT NULL,
  DESCRIPTION   VARCHAR(256),
  CLASS_NAME    VARCHAR(256) NOT NULL,
  IS_QUARTZ     CHAR(1)      NOT NULL,
  IS_REGISTERED CHAR(1)      NOT NULL,
  CREATED_AT    DATE,
  CREATED_BY    VARCHAR(15),
  UPDATED_AT    DATE,
  UPDATED_BY    VARCHAR(15)

);

CREATE TABLE BATCH_JOB_HISTORY(
  JOB_ID VARCHAR(12) NOT NULL,
  FILE_NAME VARCHAR(64) ,
  INTERFACE_FILE  MEDIUMBLOB,
  RUN_AT DATETIME NOT NULL ,
  RUN_BY VARCHAR(64) NOT NULL ,
  TIME_COST LONG NOT NULL ,
  STATUS  VARCHAR(3) NOT NULL,
  INDEX JOB_ID_IDX(JOB_ID)

);